# Generated by Django 4.2 on 2023-11-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_modeladmin_alter_speciality_courses_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelAdmin',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='work_company',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='work_company_logo',
        ),
    ]
